<?php

namespace InstagramAPI\Response\Model;

use InstagramAPI\AutoPropertyMapper;

class User extends AutoPropertyMapper
{
    const JSON_PROPERTY_MAP = [
        'username'                            => '',
        'has_anonymous_profile_picture'       => '',
        'is_favorite'                         => '',
        'profile_pic_url'                     => '',
        'full_name'                           => '',
        'user_id'                             => 'string',
        'pk'                                  => 'string',
        'id'                                  => 'string',
        'is_verified'                         => '',
        'is_private'                          => '',
        'coeff_weight'                        => '',
        'friendship_status'                   => 'FriendshipStatus',
        'hd_profile_pic_versions'             => 'ImageCandidate[]',
        'byline'                              => '',
        'search_social_context'               => '',
        'unseen_count'                        => '',
        'mutual_followers_count'              => '',
        'follower_count'                      => '',
        'social_context'                      => '',
        'media_count'                         => '',
        'following_count'                     => '',
        'is_business'                         => '',
        'usertags_count'                      => '',
        'profile_context'                     => '',
        'biography'                           => '',
        'geo_media_count'                     => '',
        'is_unpublished'                      => '',
        'allow_contacts_sync'                 => '',
        'show_feed_biz_conversion_icon'       => '',
        'profile_pic_id'                      => 'string',
        'auto_expand_chaining'                => '',
        'can_boost_post'                      => '',
        'is_profile_action_needed'            => '',
        'has_chaining'                        => '',
        'include_direct_blacklist_status'     => '',
        'can_see_organic_insights'            => '',
        'can_convert_to_business'             => '',
        'convert_from_pages'                  => '',
        'show_business_conversion_icon'       => '',
        'show_conversion_edit_entry'          => '',
        'show_insights_terms'                 => '',
        'can_create_sponsor_tags'             => '',
        'hd_profile_pic_url_info'             => 'ImageCandidate',
        'usertag_review_enabled'              => '',
        'profile_context_mutual_follow_ids'   => 'string[]',
        'profile_context_links_with_user_ids' => 'Link[]',
        'has_biography_translation'           => '',
        'business_contact_method'             => '',
        'category'                            => '',
        'direct_messaging'                    => '',
        'page_name'                           => '',
        'fb_page_call_to_action_id'           => 'string',
        'is_call_to_action_enabled'           => '',
        'public_phone_country_code'           => '',
        'public_phone_number'                 => '',
        'contact_phone_number'                => '',
        'latitude'                            => 'float',
        'longitude'                           => 'float',
        'address_street'                      => '',
        'zip'                                 => '',
        'city_id'                             => 'string',
        'city_name'                           => '',
        'public_email'                        => '',
        'is_needy'                            => '',
        'external_url'                        => '',
        'external_lynx_url'                   => '',
        'email'                               => '',
        'country_code'                        => '',
        'birthday'                            => '',
        'national_number'                     => '',
        'gender'                              => '',
        'phone_number'                        => '',
        'needs_email_confirm'                 => '',
        'is_active'                           => '',
        'block_at'                            => '',
        'aggregate_promote_engagement'        => '',
        'fbuid'                               => '',
        'page_id'                             => 'string',
        'latest_reel_media'                   => 'string',
        'has_unseen_besties_media'            => '',
        'allowed_commenter_type'              => '',
    ];
}
